#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill, then scoped to this project.
#
# 数据交换（Gitee 私有交换库 + 腾讯云 COS 私有桶）+ 判断库（judged-<机器>）+ 分析程序（DeepSeek）
# 的上机配置。编排依据：docs/ops/三机上机清单.md 第 8~14 步 + README「模型同款与判断缓存」一节。
# 可以反复跑：已配好的值从状态文件带出，回车即保留。
#
# 用法：bash tools/setup_wizard.sh                上机配置（Gitee / COS / 分析模型）
#       bash tools/setup_wizard.sh --role-change  转角色：采集机 → 纯汇总机（见 docs/adr/0034）
#       （Windows 上没有 Git Bash 的终端里，用 tools\setup_wizard.cmd，参数照传）
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES：数据交换（Gitee + COS）+ 判断库（judged-<机器>）+ 分析程序（DeepSeek）。
# 依据 docs/ops/三机上机清单.md 第 8~11、14 步与 README「模型同款与判断缓存」；
# 每步都可重跑。全部值落在：config/config.toml、config/analysis.toml、
# Gitee、腾讯云、Windows 用户环境变量、以及本脚本自己的状态文件。
# ──────────────────────────────────────────────────────────────────────────

# 两种模式：默认 = 上机配置；--role-change = 采集机转纯汇总机（口径见 docs/adr/0034）。
MODE="${1:-}"
case "$MODE" in
  ""|"--role-change") ;;
  *) printf '用法：bash tools/setup_wizard.sh [--role-change]（省略 = 上机配置）\n' >&2; exit 2 ;;
esac

# 向导从项目根跑：config/… 都按相对路径找。
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 1

# 非密钥的向导状态（Gitee 用户名/空间名、桶名）记在 .scratch（不上传）：
# 重跑时 ask 会自动把上次的值带成默认值。密钥不进这里，只进环境变量。
ENV_FILE=".scratch/setup-wizard.env"
mkdir -p .scratch
USER_ENVS=()   # 本次写入的 Windows 用户环境变量

# ── 向导自己的小工具 ──────────────────────────────────────────────────────

ok()  { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
die() { bad "$1"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# py_utf8：本项目所有 python 调用都经它——子进程默认按本机代码页（GBK）写 stdout，
# 中文在终端里就成乱码（与壳日志同款毛病）；这里统一钉成 UTF-8。
py_utf8() { PYTHONIOENCODING=utf-8 python "$@"; }

# _clean：从终端收来的值过一道——mintty（Git Bash 窗口）里按 Ctrl+V 不是粘贴，
# 它把 0x16 当字面字符插进输入（2026-09-22 实测：桶名被塞进一个 0x16，TOML 直接读不过）。
_clean() { printf '%s' "${1//[[:cntrl:]]/}"; }

# 覆盖库里的 open_url：Windows 上 explorer.exe 明明打开了也会返回非 0，原版据此把
# 「已打开」误报成「打不开」。库正文不动，这里在 stages 段换一份等价的实现。
open_url() {
  local url="$1" opener
  printf '  %s↗ %s%s\n' "$GREEN" "$url" "$RESET"
  for opener in wslview explorer.exe xdg-open open; do
    if command -v "$opener" >/dev/null 2>&1; then
      "$opener" "$url" >/dev/null 2>&1 || true
      return 0
    fi
  done
  warn "没找到能打开浏览器的命令，手动访问上面这个地址：$url"
}

# _machine_info：借项目自己的配置加载器读 [machine]（与程序同一条解析口径）。
_python_machine_info() {
  py_utf8 - <<'PY' || true
import os, sys
sys.path.insert(0, os.getcwd())   # 从项目根跑：保证 bestseller_monitor 可导入
from pathlib import Path
try:
    from bestseller_monitor.config import Config
    cfg = Config.from_file(Path("config/config.toml"))
except Exception as exc:
    print("error=" + " ".join(str(exc).split())[:300])
    sys.exit(0)
for name, value in (("machine_id", cfg.machine_id), ("role", cfg.role),
                    ("exchange_root", cfg.exchange_root), ("cos_bucket", cfg.cos_bucket),
                    ("db_file", cfg.db_file), ("data_dir", cfg.data_dir),
                    ("git_access", cfg.git_access), ("cos_access", cfg.cos_access)):
    print(f"{name}={value}")
PY
}

# _toml_get <文件> <段> <键>：读 TOML 里的字符串值（只用于提示缺省值）。
_toml_get() {
  local out
  out=$(FILE="$1" SECTION="$2" KEY="$3" py_utf8 - <<'PY'
import os, tomllib
from pathlib import Path
try:
    doc = tomllib.loads(Path(os.environ["FILE"]).read_text(encoding="utf-8"))
except Exception:
    doc = {}
node = doc
for part in os.environ["SECTION"].split("."):
    node = node.get(part, {}) if isinstance(node, dict) else {}
value = node.get(os.environ["KEY"], "") if isinstance(node, dict) else ""
print(value)
PY
)
  printf '%s' "${out//$'\r'/}"   # 剥掉 Windows 管道的 CR
}

# set_toml <文件> <段> <键> <值>：段感知地写入一个字符串值；第一次改之前先备份到
# .scratch/setup-wizard-backup/（.scratch 不进版本库，git status 也不会多出 .bak）。
set_toml() {
  local file="$1" section="$2" key="$3" value="$4" backup
  [[ -f "$file" ]] || { warn "找不到 $file，跳过写入"; return 1; }
  mkdir -p .scratch/setup-wizard-backup || return 1
  backup=".scratch/setup-wizard-backup/$(basename "$file").bak"
  [[ -f "$backup" ]] || cp -f "$file" "$backup"
  FILE="$file" SECTION="$section" KEY="$key" VALUE="$value" py_utf8 - <<'PY' || return 1
import os, re, sys
file = os.environ["FILE"]
section, key, value = (os.environ[n] for n in ("SECTION", "KEY", "VALUE"))
raw = open(file, encoding="utf-8", newline="").read()
nl = "\r\n" if "\r\n" in raw else "\n"
lines = raw.splitlines()
header, newline = f"[{section}]", f'{key} = "{value}"'
start = next((i for i, line in enumerate(lines) if line.strip() == header), None)
if start is None:
    while lines and not lines[-1].strip():
        lines.pop()
    lines += ["", header, newline]
else:
    end = next((j for j in range(start + 1, len(lines)) if re.match(r"\s*\[", lines[j])), len(lines))
    for j in range(start + 1, end):
        if re.match(rf"\s*{re.escape(key)}\s*=", lines[j]):
            lines[j] = newline
            break
    else:
        lines.insert(start + 1, newline)
open(file, "w", encoding="utf-8", newline="").write(nl.join(lines) + nl)
PY
  ok "写入 [$section] $key（$file；第一次改之前的原文件备份在 $backup）"
}

# _user_env <名>：从 Windows 用户环境变量（注册表）读值；没有就空（读不到不算错）。
# MSYS_NO_PATHCONV：Git Bash 会把 /v 这类参数当路径改写，改写过 reg 就不认了。
_user_env() {
  MSYS_NO_PATHCONV=1 reg query 'HKCU\Environment' /v "$1" 2>/dev/null \
    | sed -n 's/.*REG_[A-Z_]*[[:space:]]*//p' | head -n1 | tr -d '\r' || true
}

# set_user_env <名> <值>：写进 Windows 用户环境变量（setx）。已开的窗口读不到，要重开程序。
set_user_env() {
  local name="$1" value="$2"
  if have setx && MSYS_NO_PATHCONV=1 setx "$name" "$value" >/dev/null 2>&1; then
    USER_ENVS+=("$name")
    ok "写进用户环境变量 $name（已开着的程序读不到，需重开）"
    return 0
  fi
  SKIPPED+=("用户环境变量 $name（手动：setx $name <值>）")
  warn "写 $name 失败：请手动 setx $name <值>"
  return 1
}

# ask_secret_default <变量名> <提示> <已有值>：隐藏输入；回车保留已有值。
ask_secret_default() {
  local key="$1" prompt="$2" current="$3" input=""
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[回车保留已写入的 …%s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "${current: -4}" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_default <变量名> <提示> <缺省值>：可见输入；回车采用缺省值。
ask_default() {
  local key="$1" prompt="$2" fallback="$3" input=""
  if [[ -n "$fallback" ]]; then
    printf '  %s%s%s %s[回车 = %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$fallback" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" ]] && input="$fallback"
  printf -v "$key" '%s' "$input"
}

# pull_if_possible <克隆目录>：有上游才拉；远端还是空库时不算失败。
pull_if_possible() {
  local dir="$1"
  if git -C "$dir" rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    if git -C "$dir" pull --rebase >/dev/null 2>&1; then
      ok "$(basename "$dir")：已拉取"
    else
      warn "$(basename "$dir")：拉取失败（下一屏报告里会带上原因，多半是没权限或网络）"
    fi
  else
    note "$(basename "$dir")：远端还没有分支，没有可拉的"
  fi
}

# _clone_hint <git 的输出>：把 git 的原话翻成一句「多半是什么毛病」。
_clone_hint() {
  case "$1" in
    *"Repository not found"*|*"404 not found"*|*"does not exist"*|*"not appear to be a git repository"*)
      printf 'Gitee 说这个空间或库不存在——空间名（不是手机号）与库名对不对？' ;;
    *"Permission denied (publickey)"*|*"Permission denied"*)
      printf '公钥没登记到 Gitee，或这把 key 不在（第 2 步）' ;;
    *"Host key verification failed"*)
      printf 'Gitee 的主机指纹没记下来（手动跑一次 ssh -T git@gitee.com 并答 yes）' ;;
    *"Could not resolve hostname"*|*"Connection timed out"*|*"Connection refused"*|*"Connection reset"*)
      printf '网络到 git@gitee.com 不通' ;;
    "") printf 'git 没有输出' ;;
    *) printf '看下面 git 的原话' ;;
  esac
}

# clone_or_pull <仓库名> <strict|gentle>：已有就拉、没有就 clone。
# strict = 本机自己要用的库（失败要点名）；gentle = 名册里别的机器的库（还没建很正常）。
clone_or_pull() {
  local repo="$1" strict="${2:-gentle}" dir="$EXCHANGE_ROOT/$1" err
  if [[ -d "$dir/.git" ]]; then
    ok "$repo：已有克隆"
    pull_if_possible "$dir"
  elif [[ -e "$dir" ]]; then
    warn "$repo：$dir 已存在但不是 git 克隆，跳过（自己确认一下这个目录）"
  elif err=$(git clone "git@gitee.com:$GITEE_OWNER/$repo.git" "$dir" 2>&1); then
    ok "$repo：clone 好了"
  else
    if [[ "$strict" == "strict" ]]; then
      bad "$repo：clone 失败——$(_clone_hint "$err")"
    else
      note "$repo：没克隆上——$(_clone_hint "$err")"
    fi
    note "  git 的原话：$(printf '%s' "$err" | head -n2 | tr '\n' ' ')"
  fi
}

# verify_push <克隆目录> <空提交消息> <重跑提示>：验写权限——有提交就推现状、空库推空提交。
# 与远端一致时是空操作推送（远端照常收下这次推送请求），消息如实写出来、不冒称验过写权限。
# 返回非 0 = 没通过（调用处自己决定要不要补一句上下文）。
verify_push() {
  local dir="$1" msg="$2" hint="$3" out upstream
  if git -C "$dir" rev-parse --verify -q HEAD >/dev/null 2>&1; then
    upstream=$(git -C "$dir" rev-parse --verify -q '@{u}' 2>/dev/null || true)
    if out=$(git -C "$dir" push 2>&1); then
      if [[ -n "$upstream" && "$upstream" == "$(git -C "$dir" rev-parse HEAD)" ]]; then
        ok "$(basename "$dir")：推送通过（本地与远端一致，是空操作；远端照常收下了这次推送请求）"
      else
        ok "$(basename "$dir")：推送通过（写权限没问题）"
      fi
      return 0
    fi
    warn "$(basename "$dir")：推送失败——git 原话：$(printf '%s' "$out" | head -n1)"
    warn "  （被提示实名认证最常见；修好后重跑本向导$hint）"
    return 1
  fi
  if ! out=$(git -C "$dir" commit --allow-empty -m "$msg" 2>&1); then
    warn "$(basename "$dir")：空提交没做成——git 原话：$(printf '%s' "$out" | head -n1)"
    warn "  （全新机器多半是还没配身份：git config --global user.name \"你的名字\" 与 user.email \"你的邮箱\"；"
    warn "   配好后重跑本向导$hint）"
    return 1
  fi
  if out=$(git -C "$dir" push -u origin HEAD 2>&1); then
    ok "$(basename "$dir")：空提交推送成功（写权限通过）"
    return 0
  fi
  warn "$(basename "$dir")：推送失败——git 原话：$(printf '%s' "$out" | head -n1)"
  warn "  （被提示实名认证最常见；修好后重跑本向导$hint）"
  return 1
}

# _cos_temp <变量名前缀>：造一个只属于本次运行的小临时文件（写权限验证用）。
_COS_TMP=()
_cos_temp() {
  local tmp; tmp=$(mktemp) || return 1
  printf 'bestseller wizard check %s %s\n' "$(date)" "$1" > "$tmp"
  _COS_TMP+=("$tmp")
  printf '%s' "$tmp"
}

# cos_read_check <桶>：读通没有——列得出 img/，列不出就点名缺哪类动作。
# 「img/ 以外」那条只在读通了之后才有意义（否则它只是跟着一起失败）。
cos_read_check() {
  local bucket="$1"
  if coscli ls -r "cos://$bucket/img/" >/dev/null 2>&1; then
    ok "coscli 列得出 img/ 前缀（读通了）"
    if coscli ls -r "cos://$bucket/wizard-check-not-img/" >/dev/null 2>&1; then
      note "img/ 以外也列得出来：策略若带了桶级列目录动作（cos:GetBucket），属正常——"
      note "  要紧的是写权限限在 img/*（下面按档位验证）。手册第五节有说明。"
    else
      ok "img/ 以外被拒 = 读的范围也收在 img/ 里"
    fi
  else
    bad "coscli 列不出 cos://$bucket/img/——按顺序查：桶名（要完整桶名）？AK？策略里缺读动作？"
    note "  读动作要两处：对象级 cos:GetObject + cos:HeadObject（资源 .../img/*），"
    note "  桶级 cos:HeadBucket + cos:GetBucket（资源 .../<桶名>/*，列目录用）。见手册第五节。"
  fi
}

# cos_write_check <桶>：采集机档——传一个测试对象、取回来逐字节比对、再删掉
# （上机清单 §二 第 10 步的判据：能传能取）。
cos_write_check() {
  local bucket="$1" key="img/wizard-check-$$.txt" tmp back
  tmp=$(_cos_temp write) || { warn "造不出临时文件，跳过写验证"; return; }
  if ! coscli cp "$tmp" "cos://$bucket/$key" >/dev/null 2>&1; then
    bad "传不上去：这把 AK 缺写权限？桶名对不对？（手动跑一遍看原话）"
    return
  fi
  back=$(_cos_temp back) || back=""
  if [[ -n "$back" ]] && coscli cp "cos://$bucket/$key" "$back" >/dev/null 2>&1 && cmp -s "$tmp" "$back"; then
    ok "传得进也取得回（写权限通了）"
  else
    warn "传上去了但取不回来或内容对不上：看看读权限"
  fi
  if coscli rm "cos://$bucket/$key" >/dev/null 2>&1; then
    note "测试对象已删（$key）"
  else
    warn "测试对象没删掉，手动清一下：coscli rm cos://$bucket/$key"
    note "（采集机的策略里加上 cos:DeleteObject 就能删；程序自身不用删除权限）"
  fi
}

# cos_deny_upload_check <桶>：纯汇总机档——上传必须被拒（只读凭据的唯一硬判据）。
cos_deny_upload_check() {
  local bucket="$1" key="img/wizard-check-$$.txt" tmp
  tmp=$(_cos_temp deny) || { warn "造不出临时文件，跳过上传验证"; return; }
  if coscli cp "$tmp" "cos://$bucket/$key" >/dev/null 2>&1; then
    warn "上传居然成功了：这把 AK 不是只读——纯汇总机应只持只读凭据"
    coscli rm "cos://$bucket/$key" >/dev/null 2>&1 \
      || warn "顺手删一下：coscli rm cos://$bucket/$key"
  else
    ok "上传被拒 = COS 只读档正确"
  fi
}

if [[ ! -t 0 ]]; then
  printf '这个向导要有人在跟前：请在终端窗口里运行（bash tools/setup_wizard.sh）。\n' >&2
  exit 2
fi

# ══════════════════════════════════════════════════════════════════════════
# 转角色：采集机 → 纯汇总机（docs/adr/0034）。顺序固定：名册先撤 → 改配置 →
# 凭据真换（COS 换只读；Gitee 保留——判断库要发布判断）→ 行为自证 → 归档本机库。
# 编号、1688 账号、profile 与库都不变。
# ══════════════════════════════════════════════════════════════════════════
if [[ "$MODE" == "--role-change" ]]; then
  TOTAL_STAGES=5
  banner "转角色：采集机 → 纯汇总机（编号与库不变）"

  # ── R1/5 · 现状与原则 ───────────────────────────────────────────────────
  stage "现状与原则"
  info=$(_python_machine_info)
  info="${info//$'\r'/}"   # Windows 上 python 往管道写是 CRLF：先剥掉，免得读出来的值带 \r
  CONFIG_ERROR=$(printf '%s\n' "$info" | sed -n 's/^error=//p')
  [[ -n "$CONFIG_ERROR" ]] && die "config/config.toml 读不过：$CONFIG_ERROR"
  MACHINE_ID=$(printf '%s\n' "$info" | sed -n 's/^machine_id=//p')
  ROLE=$(printf '%s\n' "$info" | sed -n 's/^role=//p')
  EXCHANGE_ROOT=$(printf '%s\n' "$info" | sed -n 's|^exchange_root=||p'); EXCHANGE_ROOT="${EXCHANGE_ROOT//\\//}"
  COS_BUCKET=$(printf '%s\n' "$info" | sed -n 's/^cos_bucket=//p')
  DB_FILE=$(printf '%s\n' "$info" | sed -n 's|^db_file=||p'); DB_FILE="${DB_FILE//\\//}"
  DATA_DIR=$(printf '%s\n' "$info" | sed -n 's|^data_dir=||p'); DATA_DIR="${DATA_DIR//\\//}"
  say "本机编号：$MACHINE_ID    交换区根：$EXCHANGE_ROOT"
  if [[ "$ROLE" == "merge_only" ]]; then
    warn "配置里已经是纯汇总机（role = merge_only）：这一趟只做核验与归档"
  else
    say "配置里的角色：采集机（collector）——这一趟把它改成纯汇总机"
  fi
  if [[ -f "$DB_FILE" ]]; then
    hist=$(DB_PATH="$DB_FILE" py_utf8 - <<'PY' 2>/dev/null || true
import os, pathlib, sqlite3
con = sqlite3.connect(pathlib.Path(os.environ["DB_PATH"]).as_uri() + "?mode=ro", uri=True)
total, first, last = con.execute("SELECT COUNT(*), MIN(date), MAX(date) FROM inventory").fetchone()
print(f"{total} 行（{first}..{last}）")
con.close()
PY
)
    hist="${hist//$'\r'/}"
    say "本机库存：${hist:-（读不出）}"
  else
    warn "本机库不在：$DB_FILE（归档那步会跳过）"
  fi
  note "顺序不能反：名册先撤（在册即份额）→ 改配置 → 换 COS 只读凭据 → 行为自证。"
  note "还有一条铁律：**历史补发必须已经跑完再动配置**——角色一改成 merge_only，导出这半就关了"
  note "（交换台按「本机是纯汇总机，跳过」如实记），本机采集史再也发不出去。"
  note "Gitee 公钥保留不撤：判断库各写各的、与角色无关（这台还要发布判断，ADR-0039 决策 3）；"
  note "采集通道的只读由角色闸门承接——导出这半从今往后自动跳过。"
  note "编号、1688 账号、profile 都不动；库沿用不换——交换台不收本机编号那条库的包，"
  note "换新库等于基线永远回不到本机正式库。"
  pause

  # ── R2/5 · 名册先撤 ─────────────────────────────────────────────────────
  stage "名册先撤（plan 库）"
  say "名册是「谁分担采集」的唯一开关：先撤掉，免得出现「计划里归本机、但本机已不采」的空档周。"
  plan="$EXCHANGE_ROOT/plan"
  if [[ ! -d "$plan/.git" ]]; then
    warn "plan 库没 clone 到 $plan：先用上机配置模式把交换区配好，再来跑转角色"
    pause "回车继续（这步跳过）："
  elif [[ ! -f "$plan/machines.json" ]]; then
    warn "名册文件不在（$plan/machines.json）：没有什么可撤的"
    pause
  else
    pull_if_possible "$plan"
    say "现在名册：$(cat "$plan/machines.json")"
    if confirm "把 $MACHINE_ID 从名册里撤掉并推送？"; then
      if ! PLAN_DIR="$plan" MACHINE_ID="$MACHINE_ID" py_utf8 - <<'PY'
import json, os, pathlib, sys
sys.stdout.reconfigure(newline="\n")   # 直接打到终端的行也别带 Windows 的 CR
path = pathlib.Path(os.environ["PLAN_DIR"]) / "machines.json"
data = json.loads(path.read_text(encoding="utf-8-sig"))
name = os.environ["MACHINE_ID"]
data = [machine for machine in data if machine != name]
with open(path, "w", encoding="utf-8", newline="\n") as handle:   # 钉成 LF
    handle.write(json.dumps(data, ensure_ascii=False) + "\n")
print("  名册现在是：" + json.dumps(data, ensure_ascii=False))
PY
      then
        bad "名册写文件失败：plan 库没动"
      else
        git -C "$plan" add machines.json || warn "git add 失败"
        if git -C "$plan" commit -m "retire $MACHINE_ID from roster" >/dev/null 2>&1; then
          ok "名册已提交"
        else
          note "名册内容没变化（本来就不在册）"
        fi
        if git -C "$plan" push -u origin HEAD >/dev/null 2>&1; then
          ok "名册已推送"
        else
          warn "名册推送失败：手动 git -C \"$plan\" push 看原话"
        fi
        note "名册撤空时，计划生成会当场拒绝（「机器名册为空」）——下一台采集机接入的"
        note "第一件事就是把自己写进名册（上机清单第 11 步），在那之前别在别的机器上跑准备串。"
      fi
    else
      note "名册没动。"
    fi
    pause
  fi

  # ── R3/5 · 改本机配置 ───────────────────────────────────────────────────
  stage "改本机配置（config/config.toml）"
  say "把角色与两个凭据档位改成纯汇总机的值；密钥不进配置，这里只记档位。"
  say "当前：role=$(_toml_get config/config.toml machine role)　git_access=$(_toml_get config/config.toml machine git_access)　cos_access=$(_toml_get config/config.toml machine cos_access)"
  if confirm "写入 role = merge_only、git_access = read_only、cos_access = read_only？"; then
    set_toml config/config.toml machine role merge_only || warn "role 没写进去"
    set_toml config/config.toml machine git_access read_only || warn "git_access 没写进去"
    set_toml config/config.toml machine cos_access read_only || warn "cos_access 没写进去"
    note "程序每次启动都读这份配置，改完即生效。"
    note "git 档位记的是「采集通道不写」——判断库各写各的、与档位无关（判断照常发布）。"
  else
    warn "配置没改：后面的自证会按现在的角色判（多半过不去）"
  fi
  pause

  # ── R4/5 · 凭据真换：COS 换只读，Gitee 保留 ─────────────────────────────
  stage "凭据：COS 换只读（Gitee 保留）"
  say "采集通道的只读：COS 真换只读 AK（代码不校验档位，只有行为自证能证明它做对了）。"
  say "Gitee 公钥不撤——判断库要发布判断（ADR-0039 决策 3）：部署公钥只读、账号公钥全库可写，"
  say "按库收窄做不到；撤成部署公钥这台就发不了判断集。采集通道的「不写」由角色闸门承接。"
  open_url "https://console.cloud.tencent.com/cam/capi"
  step "腾讯云：新申请一把【只读】子账号 AK（Get/Head，不含上传），按 coscli 自己的帮助换上去"
  note "  旧的可写 AK 停用或删掉（它属于采集机档位）。"
  pause "换好后回车，向导来行为自证："

  # ── R5/5 · 行为自证与归档 ───────────────────────────────────────────────
  stage "行为自证与归档"
  say "三条自证：COS 上传被拒、读还是通的、判断库仍推得动（发布判断的前提）；最后把本机库归档一份。"
  judged="$EXCHANGE_ROOT/judged-$MACHINE_ID"
  if [[ -d "$judged/.git" ]]; then
    pull_if_possible "$judged"
    if ! verify_push "$judged" "verify judged write access after role change" "的转角色这趟（--role-change）"; then
      warn "判断库推不动 = 发布判断会失败：判断库的写权限不该受转角色影响，照 git 的原话修"
    fi
  else
    warn "$judged 没有克隆：跳过判断库自证（上机配置模式的第 9 步会把库备齐）"
  fi
  raw="$EXCHANGE_ROOT/raw-$MACHINE_ID"
  if [[ -d "$raw/.git" ]]; then
    pull_if_possible "$raw"
    note "采集通道的只读 = 角色闸门：交换台的导出这半按「本机是纯汇总机」跳过，不靠 Gitee 凭据"
  else
    warn "$raw 没有克隆：跳过读取核验（上机配置模式的第 4 步会把库备齐）"
  fi
  if [[ -z "$COS_BUCKET" ]]; then
    note "config 里没有 cos_bucket：COS 这半没配，跳过"
  elif ! have coscli; then
    warn "本机没有 coscli：装好后再跑一趟这一模式核验 COS 档位"
  else
    cos_read_check "$COS_BUCKET"
    cos_deny_upload_check "$COS_BUCKET"
  fi
  step "归档本机库（交换台不收本机编号的包，这份拷贝是它采集史的备份）"
  if [[ -f "$DB_FILE" ]]; then
    backup_dir="$DATA_DIR/backup"
    target="$backup_dir/bestseller-$(date +%F)-pre-role-change.db"
    if [[ -f "$target" ]]; then
      note "归档已存在，没覆盖：$target"
    elif mkdir -p "$backup_dir" && cp "$DB_FILE" "$target"; then
      ok "本机库已归档：$target"
    else
      warn "归档失败：手动把 $DB_FILE 拷到 $backup_dir"
    fi
  else
    warn "本机库不在，跳过归档"
  fi
  (( ${#_COS_TMP[@]} )) && rm -f "${_COS_TMP[@]}"
  pause

  finish
  note "转角色这趟走完了：导出这半从此按「本机是纯汇总机」跳过（入口保留），汇总、周报、分析照常；"
  note "判断集照常发布（Gitee 公钥保留），COS 已换只读。"
  note "编号、账号、profile 都没动——将来若要再采，账号与 profile 还在，改回 collector 即可。"
  exit 0
fi

TOTAL_STAGES=10
banner "数据交换 + 判断库 + 分析程序：上机配置（Gitee / COS / DeepSeek）"

# ── 1/10 · 开工检查 ───────────────────────────────────────────────────────
stage "开工检查"
say "先看本机配置与外部工具；这一步只读，不改任何东西。"
have python || die "找不到 python：先装 Python（与采集机同大版本）并加进 PATH，再跑本向导。"
have git    || die "找不到 git：先装 Git for Windows 再跑本向导。"
info=$(_python_machine_info)
info="${info//$'\r'/}"   # Windows 上 python 往管道写是 CRLF：先剥掉，免得读出来的值带 \r
CONFIG_ERROR=$(printf '%s\n' "$info" | sed -n 's/^error=//p')
[[ -n "$CONFIG_ERROR" ]] && die "config/config.toml 读不过：$CONFIG_ERROR"
MACHINE_ID=$(printf '%s\n' "$info" | sed -n 's/^machine_id=//p')
[[ -n "$MACHINE_ID" ]] || die "读不出 machine_id：确认 config/config.toml 存在、[machine] 一节按 config.example.toml 配好"
ROLE=$(printf '%s\n' "$info" | sed -n 's/^role=//p')
EXCHANGE_ROOT=$(printf '%s\n' "$info" | sed -n 's/^exchange_root=//p')
EXCHANGE_ROOT="${EXCHANGE_ROOT//\\//}"   # F:\a\b → F:/a/b：bash 与 python 都认
COS_BUCKET=$(printf '%s\n' "$info" | sed -n 's/^cos_bucket=//p')
[[ "$ROLE" == "merge_only" ]] && ROLE_CN="纯汇总机" || ROLE_CN="采集机"
say "本机 machine_id ： $MACHINE_ID（$ROLE_CN）"
say "交换区根        ： $EXCHANGE_ROOT"
say "图片桶          ： ${COS_BUCKET:-（还没配）}"
say "工具            ： python $(have python && echo '✓' || echo '✗')   git $(have git && echo '✓' || echo '✗')   ssh $(have ssh && echo '✓' || echo '✗')   coscli $(have coscli && echo '✓' || echo '✗')"
note "编号是身份：包、周计划、合并账都按 machine_id 认机器，定下来之后不该再改（见 docs/adr/0034）。"
note "刚复制配置、还没采过也没发过包的新机器，现在改是最便宜的时机。"
ask_default WANT_ID "要把本机编号改成别的吗？" "$MACHINE_ID"
WANT_ID=$(_clean "$WANT_ID")
if [[ -n "${WANT_ID:-}" && "$WANT_ID" != "$MACHINE_ID" ]]; then
  if set_toml "config/config.toml" "machine" "machine_id" "$WANT_ID"; then
    MACHINE_ID="$WANT_ID"
    ok "本机编号改为 $MACHINE_ID：后面各步都用它（clone raw-$MACHINE_ID、名册写 $MACHINE_ID）"
  fi
fi
note "向导可以反复跑：配好的值会从 $ENV_FILE 带出，回车即保留。"
note "Gitee 的私有库要推得动，账号得先完成实名认证；第一次推万一被提示，照提示做完即可。"
note "跑完本向导，细的核对判据在 docs/ops/三机上机清单.md 第 12~14 步。"
pause

# ── 2/10 · Gitee：本机 SSH key ────────────────────────────────────────────
stage "Gitee：本机 SSH key"
say "交换区的库（raw-*/plan/judged-*）走 SSH 免密访问；这一步生成（或复用）本机 ed25519 公钥，登记到 Gitee。"
KEY_FILE="$HOME/.ssh/id_ed25519"
if [[ ! -f "$KEY_FILE" ]]; then
  mkdir -p "$HOME/.ssh"
  step "本机还没有 ed25519 公钥，向导现在生成一把（空口令，供程序免密推送）"
  ssh-keygen -t ed25519 -C "$MACHINE_ID collector" -f "$KEY_FILE" -N "" >/dev/null \
    || die "ssh-keygen 失败；看看 ~/.ssh 目录是不是不可写"
  ok "已生成 $KEY_FILE"
else
  ok "已有 $KEY_FILE，直接用这一把"
fi
if [[ ! -f "$KEY_FILE.pub" ]]; then
  if ssh-keygen -y -f "$KEY_FILE" > "$KEY_FILE.pub.tmp" 2>/dev/null; then
    mv "$KEY_FILE.pub.tmp" "$KEY_FILE.pub"
    ok "私钥在、公钥文件缺，已从私钥重新导出"
  else
    rm -f "$KEY_FILE.pub.tmp"
    die "有私钥但导不出公钥（也许给私钥设了口令）：手动跑 ssh-keygen -y -f \"$KEY_FILE\" > \"$KEY_FILE.pub\""
  fi
fi
if have clip && cat "$KEY_FILE.pub" | clip >/dev/null 2>&1; then
  ok "公钥内容已复制到剪贴板"
fi
say "公钥内容（剪贴板若没拿到就手动选中复制）："
printf '\n%s\n\n' "$(cat "$KEY_FILE.pub")"
open_url "https://gitee.com/profile/sshkeys"
step "在 Gitee 页面上：标题随便填（如 $MACHINE_ID），公钥框里粘贴，点「确定」"
note "（找不到这个页面时：头像 → 账号设置 → 安全设置 → SSH 公钥）"
pause "贴好后回车，向导验证 SSH 连接："
attempt=0
while :; do
  attempt=$((attempt + 1))
  out=$(ssh -T -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -o NumberOfPasswordPrompts=0 git@gitee.com 2>&1) || true
  if printf '%s' "$out" | grep -qiE "Hi |successfully authenticated"; then
    ok "SSH 通过：$(printf '%s' "$out" | head -n1)"
    # Gitee 的问候语形如 "Hi 张三(@yeshuzhen)! You've successfully authenticated…"——
    # 括号里那串就是 clone 地址要用的「空间名」（不是手机号、不是邮箱）。抓出来存着。
    DETECTED_SPACE=$(printf '%s' "$out" | sed -n 's/.*(@\([^)]*\)).*/\1/p' | head -n1)
    if [[ -n "$DETECTED_SPACE" ]]; then
      write_env GITEE_SPACE "$DETECTED_SPACE"
      note "Gitee 报出的空间名：$DETECTED_SPACE（第 3 步按它拼 clone 地址）"
    else
      note "没从问候语里认出空间名，第 3 步会问你"
    fi
    break
  fi
  bad "还没通过：$(printf '%s' "$out" | head -n2 | tr '\n' ' ')"
  note "常见原因：公钥还没保存进 Gitee；复制的是私钥或少了字符；网络不通。"
  if (( attempt >= 3 )) || ! confirm "再试一次？"; then
    warn "SSH 没验通。后面的 clone 都要靠它，先修好再重跑本向导。"
    pause "回车先继续（后面几步会因此失败）："
    break
  fi
done

# ── 3/10 · Gitee：交换区的私有库 ─────────────────────────────────────────
stage "Gitee：交换区的私有库"
say "交换区由这些私有库组成：各机的 raw 库（三台机器的 raw-m1/raw-m2/raw-m3 + 本机的 raw-$MACHINE_ID）+ 一个计划库（plan）；每台机器还有一本判断库（judged-，第 9 步单独建）。"
open_url "https://gitee.com/projects/new"
step "建齐这些私有库（已建过的跳过），名字一字不差：raw-m1、raw-m2、raw-m3、raw-m4、plan"
note "（空库就行，初始化不初始化都可以；以后加机器再加编号。别建成开源公开库——包里是真实经营数据）"
note "本机只 clone 自己那条 raw 库 + plan；别的 raw 库留给各自的机器，向导会照名册把它们的库也备上。"
if [[ "$ROLE" == "merge_only" ]]; then
  note "你这台是纯汇总机：库由采集机建；本机公钥注册为主账号公钥（判断库要发布判断，第 9 步验）。"
  note "采集通道的只读不靠 Gitee 凭据（部署公钥只读、账号公钥全库可写，按库收窄做不到）："
  note "COS 换只读 AK，raw 的「不写」由角色闸门承接（导出这半自动跳过）。"
fi
DETECTED_SPACE=$(_existing GITEE_SPACE || true)
if [[ -n "$DETECTED_SPACE" ]]; then
  say "Gitee 回话里的空间名：$DETECTED_SPACE"
  note "clone 地址形如 git@gitee.com:$DETECTED_SPACE/<库名>.git —— 空间名不是手机号、也不是邮箱。"
else
  warn "没抓到空间名：先在 Git Bash 里跑一次 ssh -T git@gitee.com，回话里 (@名字) 那串就是空间名。"
fi
ask_default GITEE_OWNER "库所在空间（个人空间直接回车；建在组织下才填组织名）" "${DETECTED_SPACE:-$(_existing GITEE_OWNER || true)}"
GITEE_OWNER=$(_clean "$GITEE_OWNER")
[[ -n "${GITEE_OWNER:-}" ]] || die "空间名是空的：向导拼不出 clone 地址"
write_env GITEE_OWNER "$GITEE_OWNER"
note "clone 地址将按 git@gitee.com:$GITEE_OWNER/<库名>.git 拼。"
pause "五只库都建好后回车，向导去 clone："

# ── 4/10 · 交换区：clone 与写权限 ─────────────────────────────────────────
stage "交换区：clone 交换库"
say "clone 到 $EXCHANGE_ROOT：plan + 本机的 raw 库 + 名册里其它机器的 raw 库"
mkdir -p "$EXCHANGE_ROOT" || die "建不出交换区根：$EXCHANGE_ROOT"
plan="$EXCHANGE_ROOT/plan"
# 先探一下空间名：Gitee 对「空间不存在」回的是 "Auth error: 404 not found!"，
# 而 clone 时这句混在输出里不好认。探到 404 就当场把话说清（这是最常见的坑）。
probe_rc=0
probe=$(git ls-remote git@gitee.com:"$GITEE_OWNER"/plan.git 2>&1) || probe_rc=$?
if (( probe_rc == 0 )); then
  ok "空间名对得上：$GITEE_OWNER（plan 库在，已有提交）"
elif (( probe_rc == 2 )); then
  ok "空间名对得上：$GITEE_OWNER（plan 库在，还是空的）"
else
  bad "查不到 git@gitee.com:$GITEE_OWNER/plan.git：$(printf '%s' "$probe" | head -n2 | tr '\n' ' ')"
  if [[ -n "${DETECTED_SPACE:-}" && "$DETECTED_SPACE" != "$GITEE_OWNER" ]]; then
    warn "空间名恐怕写错了：本机用的是 $GITEE_OWNER，而 Gitee 回话里的空间名是 $DETECTED_SPACE"
    note "  改第 3 步的空间名（或改 $ENV_FILE 里的 GITEE_OWNER）后重跑本向导。"
  else
    note "  核对：库名一字不差？五只库都建在 $GITEE_OWNER 这个空间下？"
  fi
  pause "回车继续（多半会 clone 失败，先看一眼上面这句）："
fi
clone_or_pull plan gentle
clone_or_pull "raw-$MACHINE_ID" strict
if [[ -f "$plan/machines.json" ]]; then
  others=$(MACHINES_FILE="$plan/machines.json" py_utf8 - <<'PY' 2>/dev/null || true
import json, os, pathlib
try:
    data = json.loads(pathlib.Path(os.environ["MACHINES_FILE"]).read_text(encoding="utf-8-sig"))
except Exception:
    data = []
print("\n".join(str(machine).strip() for machine in data if str(machine).strip()))
PY
)
  others="${others//$'\r'/}"
  for id in $others; do
    if [[ "$id" != "$MACHINE_ID" ]]; then
      clone_or_pull "raw-$id" gentle
    fi
  done
else
  note "plan 库还没有名册（第一次就在这台机器上跑时正常）：等名册写好后重跑本向导，会把别家的库补上"
fi
step "写权限验证：往本机的 raw 库推一笔（空库推一个空提交，非空库推现状）"
raw="$EXCHANGE_ROOT/raw-$MACHINE_ID"
if [[ -d "$raw/.git" ]]; then
  if [[ "$ROLE" == "merge_only" ]]; then
    pull_if_possible "$raw"
    note "纯汇总机不验 raw 的 push：Gitee 凭据保留可写是为判断库（第 9 步验它），"
    note "采集通道的「不写」由角色闸门承接——交换台的导出这半按「本机是纯汇总机」跳过。"
  else
    pull_if_possible "$raw"
    verify_push "$raw" "verify write access" "第 4 步" || true
  fi
else
  warn "$raw 没克隆成功，跳过写权限验证"
fi
pause

# ── 5/10 · COS：私有桶与 img/* 限额 AK ────────────────────────────────────
stage "COS：私有桶与 img/* 限额 AK"
say "图片走腾讯云 COS 私有桶（key 形如 img/<哈希前2位>/<哈希>.<扩展名>）；这步配桶与最小权限 AK。"
note "这一屏只列要点；逐步的点击路径（建桶 → 子账号与策略 → coscli → 自证）在"
note "  docs/ops/腾讯云COS上机手册.md"
open_url "https://console.cloud.tencent.com/cos/bucket"
step "建一个【私有】桶（名字如 bestseller-exchange，控制台会补 -<APPID>），记住完整桶名与地域"
open_url "https://console.cloud.tencent.com/cam/capi"
if [[ "$ROLE" == "merge_only" ]]; then
  step "访问管理里建一把【子账号】密钥（勾「编程访问」），自定义策略只给该桶 img/* 的【只读】；别勾预设的全读写"
else
  step "访问管理里建一把【子账号】密钥（勾「编程访问」），自定义策略只给该桶 img/* 的读 + 写 + 删除；别勾预设的全读写"
fi
note "  资源照抄（地域 / APPID / 桶名换成自己的；APPID 就是完整桶名里 - 后面那串）："
note "    qcs::cos:ap-guangzhou:uid/1250000000:bestseller-exchange-1250000000/img/*"
note "  删除权限只为清掉验证用的测试对象；程序自身不删图片。"
step "装 coscli（https://github.com/tencentyun/coscli 下 exe，改名 coscli.exe 放进一个已在 PATH 的目录），再 coscli config init 填这把密钥"
note "  （放哪个目录、怎么验证：docs/ops/腾讯云COS上机手册.md 第三节；密钥落在 ~/.cos.yaml，不进代码仓）"
pause "桶建好、AK 配好后回车，向导来验证："
ask COS_BUCKET "桶名（形如 bestseller-exchange-1250000000）："
COS_BUCKET=$(_clean "$COS_BUCKET")
if [[ -z "${COS_BUCKET:-}" ]]; then
  warn "没填桶名：交换照发结构化包，图片这半按「没配」如实报缺；config.toml 留空是合法状态"
else
  if ! have coscli; then
    warn "本机没有 coscli：装好并按它自己的帮助配好 AK 后，重跑本向导第 5 步"
  elif [[ "$ROLE" == "merge_only" ]]; then
    cos_read_check "$COS_BUCKET"          # 读要通（img/ 以外列得出只作提示，不算错）
    cos_deny_upload_check "$COS_BUCKET"   # 只读档：上传必须被拒
  else
    cos_read_check "$COS_BUCKET"          # 读要通（img/ 以外列得出只作提示，不算错）
    cos_write_check "$COS_BUCKET"         # 采集机档：还要真的传得进、取得回
  fi
  (( ${#_COS_TMP[@]} )) && rm -f "${_COS_TMP[@]}"
  write_env COS_BUCKET "$COS_BUCKET"
  set_toml "config/config.toml" "machine" "cos_bucket" "$COS_BUCKET" || warn "桶名写进 config.toml 失败，手动补：machine.cos_bucket"
fi
pause

# ── 6/10 · 名册：plan 库的 machines.json ──────────────────────────────────
stage "名册：plan 库的 machines.json"
say "名册决定下一份周计划里哪些机器分担采集；顺序即平局顺序。"
plan="$EXCHANGE_ROOT/plan"
if [[ ! -d "$plan/.git" ]]; then
  warn "plan 库还没 clone（第 4 步没成）：先修好第 4 步再回来"
else
  pull_if_possible "$plan"
  if [[ -f "$plan/machines.json" ]]; then
    say "现有名册：$(cat "$plan/machines.json")"
  else
    note "plan 库还没有名册文件，将新建一份"
  fi
  if confirm "把 $MACHINE_ID 写进名册并推送？（在册的机器从下一份计划起分担采集）"; then
    if ! PLAN_DIR="$plan" MACHINE_ID="$MACHINE_ID" py_utf8 - <<'PY'
import json, os, pathlib, sys
sys.stdout.reconfigure(newline="\n")   # 直接打到终端的行也别带 Windows 的 CR
path = pathlib.Path(os.environ["PLAN_DIR"]) / "machines.json"
data = json.loads(path.read_text(encoding="utf-8-sig")) if path.is_file() else []
name = os.environ["MACHINE_ID"]
if name not in data:
    data.append(name)
with open(path, "w", encoding="utf-8", newline="\n") as handle:   # 钉成 LF：别让 Windows 写 CRLF
    handle.write(json.dumps(data, ensure_ascii=False) + "\n")
print("  名册现在是：" + json.dumps(data, ensure_ascii=False))
PY
    then
      bad "名册写文件失败：plan 库没动"
    else
      git -C "$plan" add machines.json || warn "git add 失败"
      if git -C "$plan" commit -m "add machine roster: $MACHINE_ID" >/dev/null 2>&1; then
        ok "名册已提交"
      else
        note "名册内容没变化（本来就在册）"
      fi
      if git -C "$plan" push -u origin HEAD >/dev/null 2>&1; then
        ok "名册已推送"
      else
        warn "名册推送失败：手动 git -C \"$plan\" push 看原话（实名认证最常见）"
      fi
      note "共享店铺清单（shops.csv）不用手推：第一次打开采集程序时准备串会自动同步。"
    fi
  else
    note "名册没动。"
  fi
fi
pause

# ── 7/10 · 分析模型：DeepSeek key 与 analysis.toml ────────────────────────
stage "分析模型：DeepSeek key 与 analysis.toml"
say "分析程序的「同款图像判断」用 DeepSeek：direct 模式 = 主模型直接看图（deepseek 的视觉档）。"
open_url "https://platform.deepseek.com/api_keys"
step "登录开放平台 → 左侧「API Keys」→「创建 API key」→ 复制以 sk- 开头的那串"
note "（密钥只在创建时完整显示一次；丢了就删掉重建。API 调用要余额，余额不足会报 402）"
CURRENT_KEY="$(_user_env DEEPSEEK_API_KEY)"
[[ -n "$CURRENT_KEY" ]] && note "本机用户环境变量里已有一把（…${CURRENT_KEY: -4}）；回车即保留。"
ask_secret_default DEEPSEEK_API_KEY "粘贴 DeepSeek API key：" "$CURRENT_KEY"
DEEPSEEK_API_KEY=$(_clean "$DEEPSEEK_API_KEY")
if [[ -z "${DEEPSEEK_API_KEY:-}" ]]; then
  warn "没拿到 key：模型这半跳过；拿到后重跑本向导第 7 步。"
else
  # 先验形状、再真调一次 /models：无效就当场说清、也不写进环境变量——
  # 别等第 8 步的视觉核验才发现（那一步只会给你一句被脱敏过的「请求失败」）。
  key_ok=1
  MODELS_AVAILABLE=""
  [[ "$DEEPSEEK_API_KEY" == sk-* ]] || { warn "这串不以 sk- 开头——DeepSeek 的密钥都以 sk- 开头"; key_ok=0; }
  key_sk_count=$(printf '%s' "$DEEPSEEK_API_KEY" | grep -o 'sk-' | wc -l | tr -d ' ')
  if (( key_sk_count > 1 )); then
    warn "这串里出现了 $key_sk_count 次 sk-，像是把多把密钥粘在了一起——只粘完整的一把"
    key_ok=0
  fi
  probe=$(DEEPSEEK_PROBE_KEY="$DEEPSEEK_API_KEY" py_utf8 - <<'PY' 2>&1 || true
import json, os, urllib.error, urllib.request
key = os.environ["DEEPSEEK_PROBE_KEY"]
request = urllib.request.Request("https://api.deepseek.com/models",
                                 headers={"Authorization": "Bearer " + key})
try:
    with urllib.request.urlopen(request, timeout=20) as response:
        names = [str(m.get("id")) for m in json.load(response).get("data", [])]
    print("OK " + "、".join(names[:10]))
except urllib.error.HTTPError as exc:
    print("HTTP" + str(exc.code) + " " + exc.read()[:200].decode("utf-8", "replace"))
except Exception as exc:
    print("ERR " + type(exc).__name__ + ": " + str(exc))
PY
)
  case "$probe" in
    OK*) MODELS_AVAILABLE="${probe#OK }"
         ok "密钥有效（这个账号可用的模型：$MODELS_AVAILABLE）" ;;
    *HTTP401*) bad "密钥无效（401）：${probe#*HTTP401 }"; key_ok=0 ;;
    *HTTP402*) warn "密钥有效但余额不足（402）——先去平台充值" ;;
    *) warn "没能验证密钥（${probe}）——网络或代理？照样先配，第 8 步还会用真调用验一次" ;;
  esac
  if (( key_ok == 1 )); then
    if [[ "$DEEPSEEK_API_KEY" != "$CURRENT_KEY" ]]; then
      set_user_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY" || true
    else
      ok "沿用已写入环境变量的那把 key"
    fi
    note "密钥只进用户环境变量：不进 config、不进页面、不进报告。"
  else
    SKIPPED+=("DeepSeek 密钥（换一把有效的，重跑第 7 步）")
    warn "这把 key 先不写进环境变量：换一把（或确认粘贴完整、只有一把）后重跑第 7 步。"
  fi
  if [[ ! -f config/analysis.toml ]]; then
    warn "没有 config/analysis.toml：先复制示例并改 database 路径（README「配置」一节）再重跑本步："
    note "    cp config/analysis.example.toml config/analysis.toml"
  else
    cur_mode=$(_toml_get config/analysis.toml matching mode)
    cur_model=$(_toml_get config/analysis.toml matching.model model)
    cur_endpoint=$(_toml_get config/analysis.toml matching.model endpoint)
    [[ -n "$cur_mode" ]] && note "现在 [matching] mode = $cur_mode"
    # 示例里的 deepseek-chat 是纯文本档、看不了图；这种情况建议值直接给视觉档。
    suggested_model="$cur_model"
    [[ -z "$suggested_model" || "$suggested_model" == "deepseek-chat" ]] && suggested_model="deepseek-flash"
    ask_default MODEL "模型名（要选能看图的那只；deepseek 官方叫 deepseek-flash）" "$suggested_model"
    MODEL=$(_clean "$MODEL")
    if [[ -n "$MODELS_AVAILABLE" && "$MODELS_AVAILABLE" != *"$MODEL"* ]]; then
      warn "「$MODEL」不在这个账号的可用模型列表里（$MODELS_AVAILABLE）——第 8 步多半会失败，回去核对名字"
    fi
    ask_default MODEL_ENDPOINT "服务地址（最终地址，重定向会被程序拒绝）" "${cur_endpoint:-https://api.deepseek.com/v1/chat/completions}"
    MODEL_ENDPOINT=$(_clean "$MODEL_ENDPOINT")
    set_toml config/analysis.toml matching mode direct || warn "mode 没写进去"
    set_toml config/analysis.toml matching.model endpoint "$MODEL_ENDPOINT" || warn "endpoint 没写进去"
    set_toml config/analysis.toml matching.model model "$MODEL" || warn "model 没写进去"
    set_toml config/analysis.toml matching.model key_env DEEPSEEK_API_KEY || warn "key_env 没写进去"
    note "改完 analysis.toml 要重启分析程序才生效。"
  fi
fi
pause

# ── 8/10 · 视觉通路实跑核验 ───────────────────────────────────────────────
stage "视觉通路实跑核验"
say "用分析程序自己的核验逻辑调一次模型：它发一张随机色块图，要求按序认色——"
say "只有真能看图的服务才过得去（这一步会真实调用一次模型）。"
verify=$(py_utf8 - <<'PY' 2>&1 || true
import os, sys
from pathlib import Path

sys.path.insert(0, os.getcwd())   # 从项目根跑：保证 bestseller_monitor 可导入


def registry_value(name):
    try:
        import winreg
    except ImportError:
        return ""
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as handle:
            return winreg.QueryValueEx(handle, name)[0]
    except OSError:
        return ""


try:
    from bestseller_monitor.analysis import AnalysisConfig
    from bestseller_monitor.matching import ImageJudge, ModelFailure
    cfg = AnalysisConfig.from_file(Path("config/analysis.toml"))
except Exception as exc:
    print("CONFIG-ERROR " + " ".join(str(exc).split())[:300]); sys.exit(0)
if cfg.matching is None or cfg.matching.mode == "disabled":
    print("DISABLED"); sys.exit(0)
key_env = cfg.matching.model.key_env
if not os.environ.get(key_env):
    value = registry_value(key_env)
    if value:
        os.environ[key_env] = value
if not os.environ.get(key_env):
    print("NOKEY " + key_env); sys.exit(0)
# 偶发的传输失败（网络抖动/限流）不该冒充「配置不对」：重试一次，两次都败才报。
# 色块读错的重试在程序自己的 verify() 里（相邻不同色 + 一次重试）。
import time
judge = ImageJudge(cfg.matching)
last = None
for attempt in range(2):
    try:
        judge.verify()
        last = None
        break
    except ModelFailure as exc:
        last = exc
        if attempt == 0:
            time.sleep(2)
    except Exception as exc:
        last = exc
        break
if last is not None:
    print("FAIL " + " ".join(str(last).split())[:300]); sys.exit(0)
print("PASS")
PY
)
verify="${verify//$'\r'/}"
case "$verify" in
  PASS)
    ok "核验通过：随机色块认对了，模型真的能看图。"
    ;;
  DISABLED)
    bad "analysis.toml 里还是 disabled：第 7 步的写入没生效？"
    note "确认 config/analysis.toml 存在，且 [matching] mode = \"direct\"。"
    ;;
  NOKEY*)
    bad "环境变量里读不到 ${verify#NOKEY }："
    note "setx 写的是「新开的程序」才读到的值；本向导这个窗口读不到是正常的。"
    note "重新双击分析壳（dist 里那只）再试；仍不行就在新开的 cmd 里 echo %${verify#NOKEY }% 看看有没有值。"
    ;;
  CONFIG-ERROR*)
    bad "analysis.toml 读不过：${verify#CONFIG-ERROR }"
    ;;
  FAIL*)
    bad "核验没过：${verify#FAIL }"
    note "对照查：402 = 余额不足（去充值）；401/403 = key 不完整或已删；"
    note "模型名写错（换回控制台里真实的名字）；网络/代理挡住 api.deepseek.com。"
    note "改完 config/analysis.toml 重跑第 7~8 步即可。"
    ;;
  *)
    bad "核验输出看不懂，原样贴出来：$verify"
    ;;
esac
pause

# ── 9/10 · 判断库：judged-<机器>（发布判断集的通道）──────────────────────
stage "判断库：judged-$MACHINE_ID"
say "判断集（模型判断与人工决定）走自己一条通道：每台生产机一本 judged-<机器> 私有库，与 raw-*、plan 并列。"
note "口径（ADR-0039 决策 3）：判断库各写各的、与角色档位无关——这台将来转纯汇总机，判断照样要发。"
note "真机判据：推自己那本成功、拉别人那本成功。「只写自己那本」是纪律，不是 Gitee 拦出来的："
note "部署公钥只读、账号公钥对名下所有库可写，按库收窄做不到；程序只写自己的库。"
open_url "https://gitee.com/projects/new"
step "在 Gitee 建私有库 judged-$MACHINE_ID（顺手把 judged-m1、judged-m2、judged-m3、judged-m4 一次建齐更好）"
note "（空库即可、必须私有——包里是判断与决定）"
pause "建好后回车，向导去 clone 本机那本并验写权限："
clone_or_pull "judged-$MACHINE_ID" strict
judged="$EXCHANGE_ROOT/judged-$MACHINE_ID"
if [[ -d "$judged/.git" ]]; then
  pull_if_possible "$judged"
  note "判据一「推自己那本成功」——下面这一推就是它："
  verify_push "$judged" "verify judged write access" "第 9 步" || true
  # 判据二「拉别人那本成功」。别人的判断库：建了才 clone——名单与采集名册解耦（spec §9），
  # 不按 machines.json 点名，按已知编号探一遍（名册里可能出现的新编号也一并带上，others 来自
  # 第 4 步的名册）；谁还没建、还没发布，收取时各给可读说明。
  judged_ids=$(printf '%s\n' m1 m2 m3 m4 ${others:-} | sort -u | tr '\n' ' ')
  for id in $judged_ids; do
    if [[ "$id" == "$MACHINE_ID" ]]; then continue; fi
    if git ls-remote "git@gitee.com:$GITEE_OWNER/judged-$id.git" >/dev/null 2>&1; then
      clone_or_pull "judged-$id" gentle
    else
      note "judged-$id：还没建（或还没到位的机器），跳过；建好后重跑本向导即可带上"
    fi
  done
else
  warn "$judged 没克隆成功：判断集的发布与收取都走不通；按上面的提示修好后重跑本向导第 9 步"
fi
pause

# ── 10/10 · 收尾：首次运行怎么核对 ────────────────────────────────────────
stage "收尾：首次运行怎么核对"
say "配置齐了。按顺序走这三趟，细判据在 docs/ops/三机上机清单.md 第 12~14 步："
# 壳的产物名在 2026-09 换过一轮（inventory_fetch / inventory_exchange / bestseller_analysis），
# 这里按 dist/ 里的实际文件点名，不写死。
shopt -s nullglob
exes=(dist/*.exe)
shopt -u nullglob
if (( ${#exes[@]} )); then
  note "dist/ 里现有的壳："
  for exe in "${exes[@]}"; do
    base="${exe##*/}"
    case "$base" in
      *analysis*) kind="分析" ;;
      *exchange*) kind="交换台" ;;
      *gui*|*fetch*) kind="采集界面" ;;
      *) kind="用途不明" ;;
    esac
    note "    $base（$kind）"
  done
else
  warn "dist/ 里还没有壳 exe：先按上机清单 §三 第 2 步建壳："
  note "    python tools/build_exe.py --target gui / --target exchange / --target analysis"
fi
step "1) 双击采集界面的壳（等价 python gui.py）：准备串会 pull 计划库 → 同步共享店铺清单 → 生成并发布本周计划；开始页默认勾选 = 归 $MACHINE_ID 的店"
step "2) 双击交换台的壳（等价 python exchange.py --window）→ 点「导出&汇总」：看结局行（退出码 0 干净 / 1 有需要看一眼的 / 2 本机没做成事）"
note "   往里补历史周（09-05 起，脚本入口不接在壳上）："
note "     python exchange.py --week 2026-W36"
note "     python exchange.py --week 2026-W37"
step "3) 双击分析壳（等价 python analyze.py）：同款确认页里模型能给出建议"
note "换模型、换地址只改 config/analysis.toml，改完重启分析程序；密钥始终只在环境变量里。"
note "将来这台机器转纯汇总机时跑：bash tools/setup_wizard.sh --role-change"
note "  （名册先撤 → 改配置 → 换 COS 只读凭据 → 行为自证与归档；Gitee 公钥保留——判断库要发判断，编号、账号、profile 与库都不变）"
pause "看完按回车收工："

finish

if (( ${#USER_ENVS[@]} )); then
  note "已写 Windows 用户环境变量：${USER_ENVS[*]}"
  note "  · 已经开着的程序读不到它；重新双击壳 / 重开终端才生效。"
fi
note "向导状态（Gitee 用户名、空间名、桶名）在 $ENV_FILE —— 重跑会自动带出上次的值。"
note "模型密钥不在任何文件里，只在本机用户环境变量。"
